controller_list:
  - name: fake_Brazo_controller
    joints:
      - base_link__link01
      - link01__link02
      - link01__link05
      - link05__link06
      - link06__wrist1
      - joint_wrist1__wrist2