controller_list:
  - name: arm_controller
    action_ns: myrobot/Brazo/follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_link_link01
      - link01__link02
      - link01__link05
      - link05__link06
      - link06__wrist1
      - joint_wrist1__wrist2
